# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Setup MariaDB
      - uses: getong/mariadb-action@v1.11
        with:
          #host port: 3800 # Optional, default value is 3306. The port of host
          #container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          #mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
          mysql database: 'DemoAppAuth_Test' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'Secured321*' # Required if "mysql user" is empty, default is empty. The root superuser password
          #mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          #mysql password: ${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build AuthEF.sln --no-restore --configuration Release --no-incremental
    - name: Test
      run: dotnet test -m:1 AuthEF.sln --no-build --verbosity normal --configuration Release --filter FullyQualifiedName!~RemoteTests
    - name: Powershell version
      run: (get-host).version
